@echo off
echo Starting Spring Boot Backend Server...
start cmd /k "cd spring-backend && .\mvnw.cmd spring-boot:run"

echo Starting Frontend Dev Server...
start cmd /k "cd frontend && npm run dev"

echo System is starting up...
