server.port=8080
spring.data.mongodb.uri=mongodb+srv://chamathdew2026_db_user:xEV5cvPdMYsBsY0Q@cluster0.dfhdcbj.mongodb.net/hiru_resorts?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=hiru_resorts
